### PR TITLE
Remove or replace cchardet with chardet

### LINKED ISSUE #543: cchardet alternatives for python 3.11+
**Describe the bug**
For python 3.11  cChardet fails to build.  The error message is: `cchardet.cpp(196): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or directory.`

In addition, the cchardet doesn't seem to be currently maintained. 

This is a problem that will need to be resolved going forward.
`faust-streaming/cChardet` is a possible replacement.  It is a fork of cChardet.  
https://pypi.org/project/faust-cchardet/
https://github.com/faust-streaming/cChardet

**Notes**
Does not Support
[Anaconda](https://www.anaconda.com/)
[pyenv](https://github.com/pyenv/pyenv)

Does not yet install on MacOS
Cannot install on arm64 (Apple M1 Sillicon) #12

**To Reproduce**
- Add "3.11" to ci-test.yml on a dev branch and push to Github 
- GitHub->Actions->Python CI should fail for 3.11 image when trying to build cChardet.

**Expected behavior**
Python 3.11 builds/test on  GitHub->Actions->Python CI should should pass

**Software versions (please complete the following information):**
 - Python version: [3.11]
 - Python distribution: [GitHub]
 - lasio version: 0.30

**Additional context**
- I think `chardet` is a slower fall back option.  So there is a possibility that Lasio code/packaging can be arranged to use `chardet` on Python 3.11.

### PR DESCRIPTION
**Pull request by dcslagel**
#### Description:

This branch resolves #543 

This branch removes cchardet which didn't compile on some platforms for Python 3.11 and isn't currently maintains
It replaces cchardet with chardet which is maintained.  Chardet is a little slower but this is compensated for with the general speed up of recent Python versions 3.10, and 3.11.
Python 3.11 is re-added to the GitHub Actions test for both Ubuntu and Windows.  So with this branch Lasio is fully supporting Python 3.11.

#### Test Results:

```
---------- coverage: platform darwin, python 3.10.9-final-0 ----------
Name                       Stmts   Miss  Cover
----------------------------------------------
lasio/__init__.py             28      6    79%
lasio/convert_version.py      20     20     0%
lasio/defaults.py             12      0   100%
lasio/examples.py             42     10    76%
lasio/excel.py                88     34    61%
lasio/exceptions.py            6      0   100%
lasio/las.py                 495     64    87%
lasio/las_items.py           220     30    86%
lasio/las_version.py          54     14    74%
lasio/reader.py              467     19    96%
lasio/writer.py              200      9    96%
----------------------------------------------
TOTAL                       1632    206    87%
Coverage XML written to file coverage.xml



--------------------------------------------------- benchmark: 1 tests --------------------------------------------------
Name (time in ms)                 Min       Max      Mean  StdDev    Median     IQR  Outliers     OPS  Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------
test_read_v12_sample_big     123.8097  125.1995  124.5452  0.4738  124.4822  0.6900       3;0  8.0292       8           1
-------------------------------------------------------------------------------------------------------------------------
```

--

Let me know if this change could be accepted (or rejected) or
needs some additional changes to be approved and merged.

Thank you,
DC

### CODE REVIEW

**Comment by dcslagel** [comment]
Moved to draft state because the `set logging level for lasio.ipynb` also needs to be updated and included in this pull-request.

**Comment by dcslagel** [comment]
Okay, returned to 'ready to review` state with the updates made to `set logging level for lasio.ipynb `.

**Review by kinverarity1 — APPROVED** [review]
Thank you
